<a href="https://colab.research.google.com/github/a-forty-two/EY-MarApr26/blob/main/01_Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The first thing we want to do is import numpy.

In [1]:
import numpy as np

Let us first define a Python list containing the ages of 6 people.

In [2]:
ages_list = [10, 5, 8, 32, 65, 43]
print(ages_list)

[10, 5, 8, 32, 65, 43]


In [4]:
dir(ages_list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

There are 3 main ways to instantiate a Numpy ndarray object. One of these is to use `np.array(<collection>)`

In [5]:
ages = np.array(ages_list)
print(type(ages))
print(ages)

<class 'numpy.ndarray'>
[10  5  8 32 65 43]


In [6]:
dir(ages)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',


In [7]:
print(ages)
print("Size:\t" , ages.size)
print("Shape:\t", ages.shape)

# 6, implies 6 values in 1 dimension (1-D tensor, Vector)
# Numpy converts a regular python list into a 1-D Vector

# 1-D vector is the default input of a neurons inside a neural network (LLMs, Gen AI, Agentic AI)

[10  5  8 32 65 43]
Size:	 6
Shape:	 (6,)


In [20]:
zeroArr = np.zeros(5)
print(zeroArr)

[0. 0. 0. 0. 0.]


### Multi-dim

Now let us define a new list containing the weights of these 6 people.

In [16]:
weight_list = [32, 18, 26, 60, 55, 100]

In [18]:
weight_list2 = [32, 18, 26, 60, 55]
people = [ages_list, weight_list2]

Now, we define an ndarray containing all fo this information, and again print the size and shape of the array.

In [22]:
people = np.array([ages_list, weight_list])

print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

# 2 dimensions with 6 vectors each is represented as (2,6)

People:	 [[ 10   5   8  32  65  43]
 [ 32  18  26  60  55 100]]
Size:	 12
Shape:	 (2, 6)


In [25]:
# 2 X 6 = 1 X 12 = 4 X 3 = 3 X 4 = 12 X 1

people = people.reshape(2,6)
print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [[ 10   5   8  32  65  43]
 [ 32  18  26  60  55 100]]
Size:	 12
Shape:	 (2, 6)


###### Note: The new shape must be the same "size" as the old shape

### Exercise

* Generate a 1D numpy array with the values [7, 9, 65, 33, 85, 99]

* Generate a matrix (2D numpy array) of the values:

\begin{align}
  \mathbf{A} =
  \begin{pmatrix}
    1 & 2 & 4 \\
    2 & 3 & 0 \\
    0 & 5 & 1
  \end{pmatrix}
\end{align}

* Change the dimensions of this array to another permitted shape

## Array Generation

Instead of defining an array manually, we can ask numpy to do it for us.

The `np.arange()` method creates a range of numbers with user defined steps between each.

In [26]:
five_times_table = np.arange(0, 55, 5)
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

The `np.linspace()` method will produce a range of evenly spaced values, starting, ending, and taking as many steps as you specify.

In [27]:
five_spaced = np.linspace(0,50,11)
print(five_spaced)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


The `.repeat()` method will repeat an object you pas a specified number of times.

In [28]:
twoArr = np.repeat(2, 10)
print(twoArr)

[2 2 2 2 2 2 2 2 2 2]


The `np.eye()` functions will create an identity matrix/array for us.

In [29]:
identity_matrix = np.eye(6)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


# Operations

There are many, many operations which we can perform on arrays. Below, we demonstrate a few.

What is happening in each line?

In [30]:
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [31]:
print("1:", 2 * five_times_table)
print("2:", 10 + five_times_table)
print("3:", five_times_table - 1)
print("4:", five_times_table/5)
print("5:", five_times_table **2)
print("6:", five_times_table < 20)

1: [  0  10  20  30  40  50  60  70  80  90 100]
2: [10 15 20 25 30 35 40 45 50 55 60]
3: [-1  4  9 14 19 24 29 34 39 44 49]
4: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
5: [   0   25  100  225  400  625  900 1225 1600 2025 2500]
6: [ True  True  True  True False False False False False False False]


### Speed Test

If we compare the speed at which we can do these operations compared to core python, we will notice a substantial difference.

In [34]:
fives_list = list(range(0,50,5))
print(fives_list)

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45]


In [35]:
five_times_table_lge = np.arange(0,5001,5)
five_times_table_lge

array([   0,    5,   10, ..., 4990, 4995, 5000])

In [36]:
%timeit five_times_table_lge + 5

1.67 µs ± 364 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [37]:
%timeit [e + 5 for e in fives_list]

339 ns ± 8.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Boolean string operations can also be performed on ndarrays.

In [38]:
words = np.array(["ten", "nine", "eight", "seven", "six"])

print(np.isin(words, 'e'))

print("e" in words)
["e" in word for word in words]

[False False False False False]
False


[True, True, True, True, False]

# Transpose

In [39]:
people.shape = (2, 6)
print(people, "\n")
print(people.T)

[[ 10   5   8  32  65  43]
 [ 32  18  26  60  55 100]] 

[[ 10  32]
 [  5  18]
 [  8  26]
 [ 32  60]
 [ 65  55]
 [ 43 100]]


# Data Types

As previously mentioned, ndarrays can only have one data type. If we want to obtain or change this, we use the `.dtype` attribute.

In [40]:
people.dtype

dtype('int64')

What is the data type of the below ndarray?

In [41]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
ages_with_strings

array(['10', '5', '8', '32', '65', '43'], dtype='<U21')

What is the dtype of this array?

In [42]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'], dtype='int32')
ages_with_strings

array([10,  5,  8, 32, 65, 43], dtype=int32)

What do you think has happened here?

In [47]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
ages_with_floats = np.array([10, 5, 8, 0.2, 0.3, 0.22])
print(ages_with_strings)
# if there is even 1 string value in np.array, it will cast all values to string

['10' '5' '8' '32' '65' '43']


In [48]:
ages_with_strings.dtype = 'int32'
print(ages_with_strings)

[49 48  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 53  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 56  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 51 50  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0 54 53  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0 52 51  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0]


In [49]:
ages_with_strings.size

126

In [50]:
ages_with_strings.size/21

6.0

In [51]:
np.array([10, 5, 8, '32', '65', '43']).size

6

The correct way to have changed the data type of the ndarray would have been to use the `.astype()` method, demonstrated below.

In [58]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)
print(ages_with_strings.astype('int32'))
print(ages_with_strings) # no change to original value!

['10' '5' '8' '32' '65' '43']
[10  5  8 32 65 43]
['10' '5' '8' '32' '65' '43']


### Exercise

* #### Create an array of string numbers, but use dtype to make it an array of floats.
* #### Transpose the matrix, printing the new size and shape.
* #### Use the .astype() method to convert the array to boolean.

## Array Slicing Operations

As before, we can use square brackets and indices to access individual values, and the colon operator to slice the array.

In [53]:
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [54]:
five_times_table[0]

np.int64(0)

In [55]:
five_times_table[-1]

np.int64(50)

In [59]:
five_times_table[:4] # : symbol represents beginning or end

# :4 means from beginning till the n-1th index, which is 3

array([ 0,  5, 10, 15])

In [60]:
five_times_table[4:] # from 4th index till the end

array([20, 25, 30, 35, 40, 45, 50])

In [66]:
five_times_table[ 2:5] # 2:5 from 2nd till 4th (n-1)

array([10, 15, 20])

We can also slice an n-dim ndarray., specifying the slice operation accross each axis.

In [65]:
print(people)
print(people.reshape(4,3))
xyz = people.reshape(4,3)
xyz[:3, :2] # rows-> from beginning till 3rd row, columns-> from beginning till 2nd column


[[ 10   5   8  32  65  43]
 [ 32  18  26  60  55 100]]
[[ 10   5   8]
 [ 32  65  43]
 [ 32  18  26]
 [ 60  55 100]]


array([[10,  5],
       [32, 65],
       [32, 18]])

### Exercise

* Create a numpy array with 50 zeros
* Create a np array of 2 repeated 20 times
* Create a numpy array from 0 to 2 $\pi$ in steps of 0.1

For one of the arrays generated:
* Get the first five values
* Get the last 3 values
* Get the 4th value to the 7th value

We can reverse an array by using `.flip()` or by using the `::` operator.

In [ ]:
reverse_five_times_table = np.flip(five_times_table)
reverse_five_times_table

In [ ]:
reverse_five_times_table = five_times_table[-1::-1]
print(reverse_five_times_table)
five_times_table

We can also use the `::` operator to select steps of the original array.

In [ ]:
five_times_table[0::3] #Every 3rd element starting from 0

### Exercise
Take one of the arrays you defined and
* #### Reverse it
* #### Only keep every 4th element.
* #### Get every 2nd element, starting from the last and moving backwards.

# Stats

In [67]:
np.array([1.65432, 5.98765]).round(2)

array([1.65, 5.99])

In [68]:
nums = np.arange(0, 4, 0.2555)

### Exercise

* Compute min, max, sum, mean, median, variance, and standard deviation of the above array, all to to 2 decimal places.

In [69]:
print("min = ", np.min(nums).round(2))
print("max = ", np.max(nums).round(2))
print("sum = ", np.sum(nums).round(2))
print("mean = ", np.mean(nums).round(2))
print("median = ", np.median(nums).round(2))
print("var = ", np.var(nums).round(2))
print("std = ", np.std(nums).round(2))

min =  0.0
max =  3.83
sum =  30.66
mean =  1.92
median =  1.92
var =  1.39
std =  1.18


## Random

With `np.random`, we can generate a number of types of dataset, and create training data.

The below code simulates a fair coin toss.

In [ ]:
flip = np.random.choice([0,1], 10)
flip

In [ ]:
np.random.rand(10,20,9)

We can produce 1000 datapoints of a normally distributed data set by using `np.random.normal()`

In [ ]:
mu, sigma = 0, 0.1 # mean and standard deviation
s = np.random.normal(mu, sigma, 1000)

### Exercise
* Simulate a six-sided dice using numpy.random.choice(), generate a list of values you would obtain from 10 throws.
* Simulate a two-sided coin toss that is NOT fair: it is twice as likely to have head than tails.
